defmodule Aoc.Day08Test do
  use ExUnit.Case

  alias Aoc.Day08, as: Subject

  # replace with test data from the AoC puzzle page
  @test_data """
  ............
  ........0...
  .....0......
  .......0....
  ....0.......
  ......A.....
  ............
  ............
  ........A...
  .........A..
  ............
  ............
  """

  test "execute_part_1/1" do
    result = Subject.execute_part_1(@test_data)

    assert result == 14
  end

  test "execute_part_2/1" do
    result = Subject.execute_part_2(@test_data)

    assert result == 0
  end
end
